server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api
  routes:
   user-service:
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
