server:
  port: 80
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    garden-service:
      path: /garden-service/**
      serviceId: garden-service
  retryable: true
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMillisecond: 6000