server:
  port: 8082
logging:
  level:
   root: info
   org.springframework.web: info
spring:
  redis:
    password: 360kinder
  application:
    name: user-service
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1