server:
  port: 8082
logging:
  level:
   root: info
   org.springframework.web: info
spring:
  redis:
    password: 360kinder
  application:
    name: user-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
garden-service:
  ribbon:
    ConnectionTimeout: 250
    ReadTimeut: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1
hystrix:
  command:
    default:
     execution:
      isolation:
       thread:
        timeoutInMilliseconds: 2000
feign:
 hystrix:
  enabled: true