server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     deaultZone: http://127.0.0.1:${server.port}/eureka